---

- name: mkdir /etc/ansible/hosts
  file: path=/etc/ansible state=directory recurse=yes
  tags: ansible

- name: Copy inventory to /etc/ansible/hosts
  copy: src=files/inventory dest=/etc/ansible/hosts owner=root group=root mode=644
  tags: ansible

- name: Copy exports to /etc/exports
  copy: src=files/exports dest=/etc/exports owner=root group=root mode=644
  tags: nfs
  notify: Restart NFS

- name: Copy slurm.conf to /etc/slurm-llnl/slurm.conf
  copy: src=files/slurm.conf dest=/etc/slurm-llnl/slurm.conf owner=slurm group=slurm mode=644
  tags: slurm
  notify: Restart slurmctld
