---

- name: Install pip
  apt: 
    name: python-pip
    state: latest
    update_cache: yes
  tags: setup

- name: Install ansible via pip
  pip:
    name: ansible
    state: latest
  tags: setup

- name: Install OpenLDAP
  apt:
    name: slapd, ldap-utils
    state: latest
    update_cache: yes
  tags: setup

- name: Install python-ldap
  pip:
    name: python-ldap
    state: latest
  tags: setup
