---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html#examples
users_groups:
  - gid: 100
    name: users
    state: present
  - gid: 27
    name: sudo
    state: present
  - gid: 1002
    name: numenoreans
    state: present

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.htm
users:
  - name: mmigdal
    uid: 1003
    password: "{{ '123' | password_hash('sha512') }}"
    update_password: on_create
    state: present
    comment: mmigdal@iimcb.gov.pl
    system: no
    groups:
      - users
      - sudo
      - numenoreans
    shell: /bin/bash
