---

- hosts: all
  become: yes
  vars_files:
    - vars/global_variables.yml
    - vars/users.yml
  roles:
    - common

- hosts: headnode
  become: yes
  vars_files:
    - vars/global_variables.yml
  roles:
    - headnode

- hosts: nodes
  become: yes
  vars_files:
    - vars/global_variables.yml
  roles:
    - node
