---

vars_files: global_variables.yml

- hosts: all
  become: yes
  vars_files:
    - vars/users.yml
  roles:
    - common

- hosts: headnode
  become: yes
  roles:
    - headnode

- hosts: nodes
  become: yes
  roles:
    - node
