---
- hosts: headnode
  become: yes
  tasks:
    - name: Install pip
      apt: 
        name: python-pip
        state: latest
        update_cache: yes

    - name: Install ansible via pip
      pip:
        name: ansible
        state: latest

    - name: mkdir /etc/ansible/hosts
      file: path=/etc/ansible state=directory recurse=yes

    - name: Copy inventory to /etc/ansible/hosts
      copy: src=inventory dest=/etc/ansible/hosts owner=root group=root mode=644
